//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.sistema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuracion
    {
        public long id { get; set; }
        public float tasa { get; set; }
        public float enganche { get; set; }
        public short plazo { get; set; }
    }
}
